#include "Message.h"
#include "Audio/Audio.h"

namespace OpenLoco
{
    // clang-format off
    // 0x004F8BE4, 0x004F8B08, 0x004F8C22, 0x004F8C41, 0x004F8B84, 0x004F8BC4
    static constexpr MessageTypeDescriptor _messageTypeDescriptors[31] = {
        /* cantWaitForFullLoad,         */ { MessageCriticality::advice,          Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem,                          { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      60,    1, },
        /* industryClosingDown,         */ { MessageCriticality::general,         Audio::SoundId::newsAwww,     MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                   { MessageItemArgumentType::industry, MessageItemArgumentType::null, MessageItemArgumentType::null },        180,   2, },
        /* vehicleSlipped,              */ { MessageCriticality::advice,          Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::vehicle, MessageItemArgumentType::null, MessageItemArgumentType::null },         30,    1, },
        /* unk3,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* unk4,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* unk5,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* unk6,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* unk7,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* unk8,                        */ { MessageCriticality::minorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      180,   2, },
        /* cargoNowAccepted,            */ { MessageCriticality::advice,          Audio::SoundId::notification, MessageTypeFlags::hasFirstItem,                                                                                     { MessageItemArgumentType::station, MessageItemArgumentType::null, MessageItemArgumentType::null },         30,    1, },
        /* cargoNoLongerAccepted,       */ { MessageCriticality::advice,          Audio::SoundId::notification, MessageTypeFlags::hasFirstItem,                                                                                     { MessageItemArgumentType::station, MessageItemArgumentType::null, MessageItemArgumentType::null },         30,    1, },
        /* newCompany,                  */ { MessageCriticality::majorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem,                          { MessageItemArgumentType::company, MessageItemArgumentType::town, MessageItemArgumentType::null },         180,   4, },
        /* unableToLandAtAirport,       */ { MessageCriticality::advice,          Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem,                          { MessageItemArgumentType::vehicle, MessageItemArgumentType::station, MessageItemArgumentType::null },      30,    1, },
        /* citizensCelebrate,           */ { MessageCriticality::minorCompany,    Audio::SoundId::applause2,    MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::town, MessageItemArgumentType::town },         180,   3, },
        /* workersCelebrate,            */ { MessageCriticality::minorCompany,    Audio::SoundId::applause2,    MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem, { MessageItemArgumentType::vehicle, MessageItemArgumentType::industry, MessageItemArgumentType::industry }, 180,   3, }, 
        /* newVehicle,                  */ { MessageCriticality::general,         Audio::SoundId::newsOooh,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::vehicleTab, MessageItemArgumentType::null, MessageItemArgumentType::null },      180,   4, },
        /* companyPromoted,             */ { MessageCriticality::majorCompany,    Audio::SoundId::applause2,    MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         360,   5, },
        /* newIndustry,                 */ { MessageCriticality::general,         Audio::SoundId::newsOooh,     MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                   { MessageItemArgumentType::industry, MessageItemArgumentType::null, MessageItemArgumentType::null },        180,   2, },
        /* industryProductionUp,        */ { MessageCriticality::general,         Audio::SoundId::newsOooh,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::industry, MessageItemArgumentType::null, MessageItemArgumentType::null },        120,   2, },
        /* industryProductionDown,      */ { MessageCriticality::general,         Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::industry, MessageItemArgumentType::null, MessageItemArgumentType::null },        120,   2, },
        /* congratulationsCompleted,    */ { MessageCriticality::majorCompany,    Audio::SoundId::applause2,    MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         65535, 6, },
        /* failedObjectives,            */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         65535, 6, },
        /* haveBeenBeaten,              */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         65535, 6, },
        /* bankruptcyWarning6Months,    */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         120,   6, },
        /* bankruptcyWarning3Months,    */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         120,   6, },
        /* bankruptcyDeclared,          */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         65535, 6, },
        /* bankruptcyDeclared2,         */ { MessageCriticality::majorCompetitor, Audio::SoundId::applause2,    MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                                            { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         360,   4, },
        /* vehicleCrashed,              */ { MessageCriticality::majorCompany,    Audio::SoundId::notification, MessageTypeFlags::unk0 | MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem,                                   { MessageItemArgumentType::vehicle, MessageItemArgumentType::null, MessageItemArgumentType::null },         60,    6, },
        /* companyCheated,              */ { MessageCriticality::majorCompany,    Audio::SoundId::newsAwww,     MessageTypeFlags::hasSecondItem,                                                                                    { MessageItemArgumentType::company, MessageItemArgumentType::null, MessageItemArgumentType::null },         180,   7, },
        /* newSpeedRecord,              */ { MessageCriticality::majorCompany,    Audio::SoundId::applause2,    MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem,                          { MessageItemArgumentType::vehicle, MessageItemArgumentType::company, MessageItemArgumentType::null },      720,   5, },
        /* newSpeedRecord2,             */ { MessageCriticality::majorCompetitor, Audio::SoundId::newsOooh,     MessageTypeFlags::unk1 | MessageTypeFlags::hasFirstItem | MessageTypeFlags::hasSecondItem,                          { MessageItemArgumentType::vehicle, MessageItemArgumentType::company, MessageItemArgumentType::null },      720,   4, },
    };
    // clang-format on

    const MessageTypeDescriptor& getMessageTypeDescriptor(const MessageType type)
    {
        return _messageTypeDescriptors[enumValue(type)];
    }
}
