version: "2"
services:
  openloco-docker:
    build: .
    environment:
      - "GAMEFILES=/openloco/gamefiles"
      - "DISPLAY=192.168.1.165:0"
    volumes:
      - "./gamefiles:/openloco/gamefiles"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "~/.config/OpenLoco:/root/.config/OpenLoco"

  openloco-gcc32:
    image: openloco/openloco:ubuntu-i686
    working_dir: /openloco/bin.gcc
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=release && ninja -k0"
  openloco-clang32:
    image: openloco/openloco:ubuntu-i686
    working_dir: /openloco/bin.clang
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=release && ninja -k0"
  openloco-mingw32:
    image: openloco/openloco:fedora-mingw32
    working_dir: /openloco/bin.mingw32
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt -DCMAKE_BUILD_TYPE=release -DBOOST_ROOT=/usr/i686-w64-mingw32/sys-root/mingw/ && ninja -k0"
