version: '3'
services:
  openloco-gcc32:
    image: openrct2/openloco:ubuntu-i686
    working_dir: /openloco/bin.gcc
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_BUILD_TYPE=release && ninja -k0"
  openloco-clang32:
    image: openrct2/openloco:ubuntu-i686
    working_dir: /openloco/bin.clang
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=release && ninja -k0"
  openloco-mingw32:
    image: openrct2/openloco:fedora-mingw32
    working_dir: /openloco/bin.mingw32
    volumes:
      - .:/openloco
    entrypoint: bash
    command: -c "cmake ../ -G Ninja -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt -DCMAKE_BUILD_TYPE=release -DBOOST_ROOT=/usr/i686-w64-mingw32/sys-root/mingw/ && ninja -k0"
