#include "SurfaceData.h"
#include "SurfaceElement.h"
#include <array>

namespace OpenLoco::World
{
    // For lowering surface height
    // NB: only used by raise/lower land and mountain tools
    // 0x004FD3DC
    constexpr std::array<std::array<uint8_t, 32>, 9> lowerSurfaceCornerMapping = { {
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          SurfaceSlope::CornerDown::west,
          0,
          0,
          0,
          SurfaceSlope::CornerDown::south,
          0,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          0 },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          0,
          0,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          0,
          0,
          SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          0,
          0,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          0,
          0,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerUp::north,
          0,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north },
    } };

    // For raising surface height
    // NB: only used by raise/lower land and mountain tools
    // 0x004FD33C
    constexpr std::array<std::array<uint8_t, 32>, 9> raiseSurfaceCornerMapping = { {
        { SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment },
        { SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::south },
        { SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::east | SurfaceSlope::CornerUp::north },
        { SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerUp::south | SurfaceSlope::CornerUp::east },
    } };

    uint8_t lowerSurfaceCornerFlags(uint8_t selectedCorner, uint8_t currentSlope)
    {
        return lowerSurfaceCornerMapping[selectedCorner][currentSlope];
    }

    uint8_t raiseSurfaceCornerFlags(uint8_t selectedCorner, uint8_t currentSlope)
    {
        return raiseSurfaceCornerMapping[selectedCorner][currentSlope];
    }
}
