#include "SurfaceData.h"
#include "SurfaceElement.h"
#include <array>

namespace OpenLoco::World
{
    // For lowering surface height
    // NB: only used by raise/lower land and mountain tools
    // 0x004FD3DC
    constexpr std::array<std::array<uint8_t, 32>, 9> lowerSurfaceCornerMapping = { {
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          SurfaceSlope::CornerDown::east,
          0,
          0,
          0,
          SurfaceSlope::CornerDown::north,
          0,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          0 },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          0,
          0,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          0,
          0,
          SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          0,
          0,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          0,
          0,
          0,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north },
        { SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerRaised::south,
          0,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south },
    } };

    // For raising surface height
    // NB: only used by raise/lower land and mountain tools
    // 0x004FD33C
    constexpr std::array<std::array<uint8_t, 32>, 9> raiseSurfaceCornerMapping = { {
        { SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::doubleHeight | SurfaceSlope::CornerDown::south | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment },
        { SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::north },
        { SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::CornerDown::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::west | SurfaceSlope::CornerRaised::south },
        { SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::south,
          SurfaceSlope::CornerDown::south,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::east,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west,
          SurfaceSlope::requiresHeightAdjustment | SurfaceSlope::CornerRaised::north | SurfaceSlope::CornerRaised::west },
    } };

    uint8_t lowerSurfaceCornerFlags(uint8_t selectedCorner, uint8_t currentSlope)
    {
        return lowerSurfaceCornerMapping[selectedCorner][currentSlope];
    }

    uint8_t raiseSurfaceCornerFlags(uint8_t selectedCorner, uint8_t currentSlope)
    {
        return raiseSurfaceCornerMapping[selectedCorner][currentSlope];
    }
}
