set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PROCESSOR "i686")

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")

set(CMAKE_FIND_ROOT_PATH "/usr/lib/i386-linux-gnu")

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
